language: objective-c
sudo: false
osx_image: xcode7.1
script:
- curl -fsSL https://raw.githubusercontent.com/legoless/Dominus/master/install.sh | sh
env:
  matrix:
  - ACTION=build
  - ACTION=test
  global:
  - SDK=9.1
  - PLATFORM='iphone'
